spring.application.name=envSpecific
#provide the environment specific properties
spring.profiles.active=dev
server.port=8084


# spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb://localhost:27017/
spring.data.mongodb.database=envSpecific

# spring.data.mongodb.uri=mongodb://localhost:27017/
# spring.data.mongodb.database=envSpecific
