spring.application.name=envSpecific
#provide the environment specific properties
spring.profiles.active=dev
server.port=8084


# spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb+srv://s7-d-usr:zRcugaoe943-jUidc@devlopment.vtinu.mongodb.net/?retryWrites=true&w=majority&appName=devlopment
spring.data.mongodb.database=s7-d-v4-s1

# spring.data.mongodb.uri=mongodb://localhost:27017
# spring.data.mongodb.database=BuildLogs